image: Visual Studio 2017
environment:
  nodejs_version: "10"
platform:
  - x64
skip_tags: true
shallow_clone: true
clone_depth: 1
cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json

branches:
  only:
    - master
    - develop
    - /^hotfix\/.*$/
    - /^release\/.*$/

install:
  - ps: |
      $tmp = New-TemporaryFile
      [Convert]::FromBase64String($env:CSC_LINK) | Set-Content ($tmp.FullName + ".p12") -Encoding Byte
      $env:CSC_LINK = ($tmp.FullName + ".p12")
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set CI=true
  - yarn
  - yarn test
  - yarn e2e

build_script:
  - yarn release
